// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yyeifxhoreleenqwofab.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl5ZWlmeGhvcmVsZWVucXdvZmFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MzI4MDMsImV4cCI6MjA3MjQwODgwM30.g4Ddnk73nUwmGoEpSbw3h36gR49p83_EUPynaxyMeRE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});